# Generated by Django 4.2.1 on 2023-06-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_book_id_orderitem_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookitem',
            old_name='book_id',
            new_name='book',
        ),
    ]
