# Generated by Django 4.2.1 on 2023-06-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_book_id_bookitem_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemBookItem',
        ),
    ]
