# Generated by Django 4.2.1 on 2023-06-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_orderitembookitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookItem',
        ),
    ]
